# Generated by Django 6.0 on 2026-02-03 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annonce",
            fields=[
                ("id_annonce", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=120)),
                ("description", models.TextField()),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("JOB", "Job/Stage/Alternance"),
                            ("BONPLAN", "Bon plan"),
                            ("EVENT", "Evenement"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=10,
                    ),
                ),
                (
                    "visibilite",
                    models.CharField(
                        choices=[("PROMO", "Promo"), ("ECOLE", "Ecole")],
                        default="ECOLE",
                        max_length=5,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_expiration", models.DateTimeField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/annonces/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mot_de_passe", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ETU", "Etudiant"),
                            ("ANC", "Ancien"),
                            ("ADM", "Administrateur"),
                        ],
                        default="ETU",
                        max_length=3,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/utilisateurs/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id_reservation", models.AutoField(primary_key=True, serialize=False)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ATT", "En attente"),
                            ("ACC", "Acceptee"),
                            ("VAL", "Validee"),
                            ("REF", "Refusee"),
                        ],
                        default="ATT",
                        max_length=3,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "annonce_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="UniShare.annonce",
                    ),
                ),
                ("id_service", models.AutoField(primary_key=True, serialize=False)),
                (
                    "statut",
                    models.CharField(
                        choices=[("DISPO", "Disponible"), ("RES", "Reserve")],
                        default="DISPO",
                        max_length=5,
                    ),
                ),
                (
                    "lieu_rencontre",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("date_rencontre", models.DateTimeField(blank=True, null=True)),
            ],
            bases=("UniShare.annonce",),
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="UniShare.utilisateur",
                    ),
                ),
                ("ecole", models.CharField(max_length=255)),
                (
                    "statut_compte",
                    models.CharField(
                        choices=[("ACTIF", "Actif"), ("SUSP", "Suspendu")],
                        default="ACTIF",
                        max_length=5,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("L1", "Licence 1"),
                            ("L2", "Licence 2"),
                            ("L3", "Licence 3"),
                            ("M1", "Master 1"),
                            ("M2", "Master 2"),
                            ("DOC", "Doctorat"),
                        ],
                        default="L1",
                        max_length=3,
                    ),
                ),
                ("formation", models.CharField(max_length=255)),
                ("promo", models.CharField(max_length=20)),
            ],
            bases=("UniShare.utilisateur",),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id_notif", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=120)),
                ("message", models.TextField()),
                ("lu", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="UniShare.reservation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="UniShare.service",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="demandeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="UniShare.etudiant",
            ),
        ),
        migrations.AddField(
            model_name="annonce",
            name="auteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annonces",
                to="UniShare.etudiant",
            ),
        ),
    ]
