# Generated by Django 6.0.2 on 2026-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniShare", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="type_service",
            field=models.CharField(
                choices=[
                    ("TUTORAT", "Tutorat"),
                    ("COVOIT", "Covoiturage"),
                    ("DON", "Don d'objets"),
                    ("AUTRE", "Autre"),
                ],
                default="AUTRE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="annonce",
            name="visibilite",
            field=models.CharField(
                choices=[("PROMO", "Promo"), ("ECOLE", "Ecole"), ("PUBLIC", "Public")],
                default="PUBLIC",
                max_length=6,
            ),
        ),
    ]
