# Generated by Django 6.0.2 on 2026-02-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniShare", "0002_service_type_service_alter_annonce_visibilite"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type_notification",
            field=models.CharField(
                choices=[
                    ("RESERVATION", "Notification de réservation"),
                    ("ANNONCE", "Notification d'annonce"),
                ],
                default="ANNONCE",
                max_length=20,
            ),
        ),
    ]
