# Generated by Django 6.0.2 on 2026-02-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniShare", "0003_notification_type_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="date_demande_suppression",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="demande_suppression_en_cours",
            field=models.BooleanField(default=False),
        ),
    ]
