# Generated by Django 6.0.2 on 2026-02-22 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniShare", "0004_utilisateur_date_demande_suppression_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="UniShare.reservation",
            ),
        ),
    ]
