# Generated by Django 6.0.2 on 2026-03-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniShare", "0005_alter_notification_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="annonce",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="UniShare.annonce",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type_notification",
            field=models.CharField(
                choices=[
                    ("RESERVATION", "Notification de réservation"),
                    ("ANNONCE", "Notification d'annonce"),
                    ("RESERVATION_AUTEUR", "Notification pour l'auteur du service"),
                ],
                default="ANNONCE",
                max_length=20,
            ),
        ),
    ]
