# Generated by Django 6.0.2 on 2026-03-18 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UniShare", "0006_notification_annonce_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="annonce",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="reservation",
        ),
        migrations.AddField(
            model_name="notification",
            name="auteur",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="UniShare.utilisateur",
            ),
            preserve_default=False,
        ),
    ]
